#!/bin/bash
# Test script to drive the example external remote

set -eu -o pipefail -x

cd $(dirname "$0")

export PATH=$PWD:$PATH

TMP="$(mktemp -d "${TMPDIR:-/tmp}/gar-XXXXXXX")"
# so there is no global git config side-effects
export HOME="$TMP"

SOURCE_DATASET="file://$TMP/test-dataset"
SOURCE_DATASET_NAME="test-dataset"
REPO_DIR="$TMP/repo"
# mkdir -p "$REMOTE_DIR"
cd "$TMP"
dtool create ${SOURCE_DATASET_NAME}
mkdir -p "$REPO_DIR"

cd "$REPO_DIR"
git init
git config user.email "someuser@gmail.com"
git config user.name "Some User"
git annex init
git annex initremote --verbose --debug dtool_remote type=external externaltype=dtool encryption=none uri="${SOURCE_DATASET}"
git annex testremote --verbose --debug dtool_remote  2>&1 | tail -n 1000
